# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0e94614820529ab5610ce6d16475b714986b5a0bb28935eb3325ff4bf6dd831080922e6d8351d5c04b28a46f036d892eba4cddc18133793618aa11b8328bdc0

test:
  secret_key_base: 26820a8c6925e0d01fb404d9f3ca1ec0fa9724933c63d7fc5d10147aaaa73fed3b544768953b7115e59fb8337c9b2b519e6a245f908b4005871ecdbfb0662359

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
